export const MOCK_USER = {
  id: 'FARMER-9824',
  name: 'Suresh Gowda',
  kisanId: 'KA-MY-8924',
  phone: '+91 98451 23456',
  aadhaarMasked: 'XXXX-XXXX-8921',
  village: 'Jayapura Village, Mysore Taluk',
  district: 'Mysore',
  state: 'Karnataka',
  landHoldingAcres: 5.2,
  cropsGrown: ['Ragi (Finger Millet)', 'Paddy (Grade A)', 'Maize (Corn)'],
  bankAccount: {
    bankName: 'Canara Bank (Mysore Main Branch)',
    accountMasked: 'XXXXXXXX8492',
    ifsc: 'CNRB0001234',
    dbtLinked: true,
  },
  role: 'FARMER',
};

export const MOCK_CENTRES = [
  {
    id: 'C001',
    name: 'Mysore (Bandipalya) APMC Central Yard',
    subTitle: 'Central Grain Procurement Yard & Silo',
    location: 'Nanjangud Road, Bandipalya, Mysore, Karnataka',
    distanceKm: 7.8,
    travelTimeMinutes: 20, // at tractor speed (~25 km/h)
    activeCounters: 4,
    queueSize: 12,
    estimatedWaitMinutes: 48,
    processingTimeMinutes: 30,
    dailyCapacityQuintals: 3500,
    procuredTodayQuintals: 2150,
    acceptedCrops: ['RAGI', 'PADDY_COMMON', 'PADDY_GRADE_A', 'MAIZE', 'TUR'],
    currentServingToken: 'MY-110',
    status: 'BUSY',
    recommended: false,
    gateNo: 'Gate 2 (Tractor Entry)',
  },
  {
    id: 'C002',
    name: 'Nanjangud APMC Sub-Yard',
    subTitle: 'Modernized Automated Weighbridge Yard',
    location: 'Industrial Area Road, Nanjangud, Mysore District',
    distanceKm: 16.4,
    travelTimeMinutes: 36,
    activeCounters: 3,
    queueSize: 3,
    estimatedWaitMinutes: 12,
    processingTimeMinutes: 25,
    dailyCapacityQuintals: 2200,
    procuredTodayQuintals: 940,
    acceptedCrops: ['RAGI', 'PADDY_GRADE_A', 'MAIZE', 'GRAM'],
    currentServingToken: 'NJ-039',
    status: 'AVAILABLE',
    recommended: true, // Lowest Total Expected Time!
    recommendationReason: 'Lowest Total Time: Even though 8.6 km farther than Bandipalya, queue wait is 36 minutes faster!',
    gateNo: 'Main Gate 1',
  },
  {
    id: 'C003',
    name: 'T. Narasipura Grain Procurement Centre',
    subTitle: 'Karnataka State Millet & Food Grain Grid',
    location: 'Kollegal Main Road, T. Narasipura, Mysore District',
    distanceKm: 24.0,
    travelTimeMinutes: 48,
    activeCounters: 2,
    queueSize: 2,
    estimatedWaitMinutes: 8,
    processingTimeMinutes: 25,
    dailyCapacityQuintals: 1600,
    procuredTodayQuintals: 520,
    acceptedCrops: ['RAGI', 'PADDY_COMMON', 'MAIZE', 'SUGARCANE'],
    currentServingToken: 'TN-015',
    status: 'AVAILABLE',
    recommended: false,
    gateNo: 'East Gate',
  },
  {
    id: 'C004',
    name: 'Hunsur APMC Yard',
    subTitle: 'West Mysore Regional Procurement Facility',
    location: 'Old Mysore-Bantwal Road, Hunsur, Mysore District',
    distanceKm: 38.0,
    travelTimeMinutes: 60,
    activeCounters: 2,
    queueSize: 15,
    estimatedWaitMinutes: 65,
    processingTimeMinutes: 35,
    dailyCapacityQuintals: 2600,
    procuredTodayQuintals: 2200,
    acceptedCrops: ['RAGI', 'MAIZE', 'TUR', 'GRAM'],
    currentServingToken: 'HN-072',
    status: 'HEAVY_CONGESTION',
    recommended: false,
    gateNo: 'Gate 3',
  },
];

export const MOCK_INITIAL_BOOKINGS = [
  {
    bookingId: 'KQ-2026-8923',
    token: 'MY-117',
    centreId: 'C001',
    centreName: 'Mysore (Bandipalya) APMC Central Yard',
    gate: 'Gate 2 (Tractor Entry)',
    farmerName: 'Basavaraj N.',
    kisanId: 'KA-MY-9910',
    produceType: 'RAGI',
    cropName: 'Ragi (Finger Millet)',
    quantityQuintals: 60,
    mspRatePerQuintal: 4290,
    estimatedTotalAmount: 257400,
    slotDate: new Date().toISOString().slice(0, 10),
    slotTime: '09:00 AM - 11:00 AM',
    status: 'ARRIVED',
    arrivedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),

    initialPosition: 1,
    currentPosition: 1,
    farmersAhead: 0,
    estimatedWaitMinutes: 5,
    currentlyServing: 'MY-116',

    commuteMinutes: 15,
    commuteDistanceKm: 5.2,
    routeDesc: 'Via Nanjangud Road',
    expectedTurnTime: new Date(Date.now() + 5 * 60 * 1000).toISOString(),
    recommendedDepartureTime: new Date(Date.now()).toISOString(),

    queueTokens: [
      { token: 'MY-116', status: 'SERVING', isUser: false },
      { token: 'MY-117', status: 'ARRIVED', isUser: false },
      { token: 'MY-118', status: 'ARRIVED', isUser: true },
      { token: 'MY-119', status: 'WAITING', isUser: false },
    ],

    procurementDetails: {
      weighbridgeSlipNo: 'WB-9920',
      grossWeightQuintals: 68.0,
      tareWeightQuintals: 8.0,
      netWeightQuintals: 60.0,
      moisturePercent: '11.0% (Allowed: <12.0%)',
      foreignMatterPercent: '0.2% (Grade A)',
      verifiedByStaff: 'Inspector M. Kumar',
    },
    paymentDetails: {
      paymentRef: 'DBT-GOV-2026-99247',
      status: 'NOT_INITIATED',
      payoutAmount: 257400,
      accountMasked: 'Canara Bank ****5512',
      ifsc: 'CNRB0001234',
      dbtStatusText: 'Direct Benefit Transfer linked with Aadhaar NPCI mapper',
    },
  },
  {
    bookingId: 'KQ-2026-8924',
    token: 'MY-118',
    centreId: 'C001',
    centreName: 'Mysore (Bandipalya) APMC Central Yard',
    gate: 'Gate 2 (Tractor Entry)',
    farmerName: 'Suresh Gowda',
    kisanId: 'KA-MY-8924',
    produceType: 'RAGI',
    cropName: 'Ragi (Finger Millet)',
    quantityQuintals: 50,
    mspRatePerQuintal: 4290,
    estimatedTotalAmount: 214500,
    slotDate: new Date().toISOString().slice(0, 10),
    slotTime: '10:00 AM - 12:00 PM',
    status: 'ARRIVED',
    arrivedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),

    initialPosition: 2,
    currentPosition: 2,
    farmersAhead: 1,
    estimatedWaitMinutes: 12,
    currentlyServing: 'MY-116',

    commuteMinutes: 20,
    commuteDistanceKm: 7.8,
    routeDesc: 'Via Nanjangud Road (Tractor Speed)',
    expectedTurnTime: new Date(Date.now() + 12 * 60 * 1000).toISOString(),
    recommendedDepartureTime: new Date(Date.now()).toISOString(),

    queueTokens: [
      { token: 'MY-116', status: 'SERVING', isUser: false },
      { token: 'MY-117', status: 'ARRIVED', isUser: false },
      { token: 'MY-118', status: 'ARRIVED', isUser: true },
      { token: 'MY-119', status: 'WAITING', isUser: false },
      { token: 'MY-120', status: 'WAITING', isUser: false },
    ],

    procurementDetails: {
      weighbridgeSlipNo: 'WB-9921',
      grossWeightQuintals: 56.8,
      tareWeightQuintals: 6.8,
      netWeightQuintals: 50.0,
      moisturePercent: '11.4% (Allowed: <12.0%)',
      foreignMatterPercent: '0.3% (Grade A)',
      verifiedByStaff: 'Inspector M. Kumar',
      completedAt: null,
    },

    paymentDetails: {
      paymentRef: 'DBT-GOV-2026-99248',
      status: 'NOT_INITIATED',
      payoutAmount: 214500,
      accountMasked: 'Canara Bank ****8492',
      ifsc: 'CNRB0001234',
      dbtStatusText: 'Direct Benefit Transfer linked with Aadhaar NPCI mapper',
      disbursedAt: null,
    },
  },
  {
    bookingId: 'KQ-2026-8925',
    token: 'MY-119',
    centreId: 'C001',
    centreName: 'Mysore (Bandipalya) APMC Central Yard',
    gate: 'Gate 2 (Tractor Entry)',
    farmerName: 'Ninge Gowda',
    kisanId: 'KA-MY-3312',
    produceType: 'MAIZE',
    cropName: 'Maize (Corn)',
    quantityQuintals: 75,
    mspRatePerQuintal: 2225,
    estimatedTotalAmount: 166875,
    slotDate: new Date().toISOString().slice(0, 10),
    slotTime: '11:00 AM - 01:00 PM',
    status: 'WAITING',
    createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),

    initialPosition: 3,
    currentPosition: 3,
    farmersAhead: 2,
    estimatedWaitMinutes: 28,
    currentlyServing: 'MY-116',

    commuteMinutes: 25,
    commuteDistanceKm: 11.0,
    routeDesc: 'Via Bannur Road',
    expectedTurnTime: new Date(Date.now() + 28 * 60 * 1000).toISOString(),
    recommendedDepartureTime: new Date(Date.now() + 3 * 60 * 1000).toISOString(),

    queueTokens: [
      { token: 'MY-116', status: 'SERVING', isUser: false },
      { token: 'MY-117', status: 'ARRIVED', isUser: false },
      { token: 'MY-118', status: 'ARRIVED', isUser: true },
      { token: 'MY-119', status: 'WAITING', isUser: false },
      { token: 'MY-120', status: 'WAITING', isUser: false },
    ],

    procurementDetails: {
      weighbridgeSlipNo: 'WB-9922',
      grossWeightQuintals: 85.0,
      tareWeightQuintals: 10.0,
      netWeightQuintals: 75.0,
      moisturePercent: '11.5%',
      foreignMatterPercent: '0.4%',
      verifiedByStaff: 'Inspector M. Kumar',
    },
    paymentDetails: {
      paymentRef: 'DBT-GOV-2026-99249',
      status: 'NOT_INITIATED',
      payoutAmount: 166875,
      accountMasked: 'Union Bank ****3310',
      ifsc: 'UBIN0002211',
      dbtStatusText: 'Direct Benefit Transfer linked with Aadhaar NPCI mapper',
    },
  },
  {
    bookingId: 'KQ-2026-8926',
    token: 'TN-019',
    centreId: 'C003',
    centreName: 'T. Narasipura Grain Procurement Centre',
    gate: 'East Gate',
    produceType: 'MAIZE',
    cropName: 'Maize (Corn)',
    quantityQuintals: 40,
    mspRatePerQuintal: 2225,
    estimatedTotalAmount: 89000, // 40 * 2225
    slotDate: '2026-09-06',
    slotTime: '03:00 PM - 05:00 PM',
    status: 'WAITING',
    createdAt: '2026-09-06T09:45:00Z',

    initialPosition: 14,
    currentPosition: 14,
    farmersAhead: 13,
    estimatedWaitMinutes: 56,
    currentlyServing: 'TN-005',

    commuteMinutes: 48,
    commuteDistanceKm: 24.0,
    routeDesc: 'Via Kollegal Main Road',
    expectedTurnTime: new Date(Date.now() + 56 * 60 * 1000).toISOString(),
    recommendedDepartureTime: new Date(Date.now() + (56 - 48) * 60 * 1000).toISOString(),

    queueTokens: [
      { token: 'TN-005', status: 'SERVING', isUser: false },
      { token: 'TN-006', status: 'WAITING', isUser: false },
      { token: 'TN-007', status: 'WAITING', isUser: false },
      { token: 'TN-008', status: 'WAITING', isUser: false },
      { token: 'TN-009', status: 'WAITING', isUser: false },
      { token: 'TN-010', status: 'WAITING', isUser: false },
      { token: 'TN-011', status: 'WAITING', isUser: false },
      { token: 'TN-012', status: 'WAITING', isUser: false },
      { token: 'TN-013', status: 'WAITING', isUser: false },
      { token: 'TN-014', status: 'WAITING', isUser: false },
      { token: 'TN-015', status: 'WAITING', isUser: false },
      { token: 'TN-016', status: 'WAITING', isUser: false },
      { token: 'TN-017', status: 'WAITING', isUser: false },
      { token: 'TN-018', status: 'WAITING', isUser: false },
      { token: 'TN-019', status: 'WAITING', isUser: true },
      { token: 'TN-020', status: 'WAITING', isUser: false },
    ],

    procurementDetails: {
      weighbridgeSlipNo: 'WB-9929',
      grossWeightQuintals: 46.5,
      tareWeightQuintals: 6.5,
      netWeightQuintals: 40.0,
      moisturePercent: '11.2% (Allowed: <12.0%)',
      foreignMatterPercent: '0.3% (Grade A)',
      verifiedByStaff: 'Inspector P. Shinde',
      completedAt: null,
    },

    paymentDetails: {
      paymentRef: 'DBT-GOV-2026-99250',
      status: 'NOT_INITIATED',
      payoutAmount: 89000,
      accountMasked: 'Canara Bank ****8492',
      ifsc: 'CNRB0001234',
      dbtStatusText: 'Direct Benefit Transfer linked with Aadhaar NPCI mapper',
      disbursedAt: null,
    },
  },
  {
    bookingId: 'KQ-2026-8920',
    token: 'MY-115',
    centreId: 'C001',
    centreName: 'Mysore (Bandipalya) APMC Central Yard',
    gate: 'Gate 2 (Tractor Entry)',
    farmerName: 'Mahadevappa B.',
    kisanId: 'KA-MY-7712',
    produceType: 'RAGI',
    cropName: 'Ragi (Finger Millet)',
    quantityQuintals: 80,
    mspRatePerQuintal: 4290,
    estimatedTotalAmount: 343200,
    slotDate: new Date().toISOString().slice(0, 10),
    slotTime: '08:00 AM - 10:00 AM',
    status: 'PROCURED',
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    procurementDetails: {
      weighbridgeSlipNo: 'WB-9912',
      grossWeightQuintals: 92.5,
      tareWeightQuintals: 12.5,
      netWeightQuintals: 80.0,
      moisturePercent: '10.8% (Allowed: <12.0%)',
      foreignMatterPercent: '0.2% (Grade A)',
      verifiedByStaff: 'Inspector M. Kumar',
      completedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    },
    paymentDetails: {
      paymentRef: 'DBT-GOV-2026-88001',
      status: 'DISBURSED',
      payoutAmount: 343200,
      accountMasked: 'SBI ****9012',
      ifsc: 'SBIN0004012',
      dbtStatusText: 'Direct Benefit Transfer Completed via Aadhaar NPCI',
      disbursedAt: new Date(Date.now() - 3600000 * 1.5).toISOString(),
    },
  },
  {
    bookingId: 'KQ-2026-8921',
    token: 'MY-116',
    centreId: 'C001',
    centreName: 'Mysore (Bandipalya) APMC Central Yard',
    gate: 'Gate 2 (Tractor Entry)',
    farmerName: 'Ramesh K.',
    kisanId: 'KA-MY-4519',
    produceType: 'PADDY_GRADE_A',
    cropName: 'Paddy (Grade A)',
    quantityQuintals: 45,
    mspRatePerQuintal: 2320,
    estimatedTotalAmount: 104400,
    slotDate: new Date().toISOString().slice(0, 10),
    slotTime: '09:00 AM - 11:00 AM',
    status: 'REJECTED',
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    rejectedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    rejectionReason: 'Moisture content 15.8% exceeds mandatory FAQ limit of 12.0%. Recommended solar drying.',
    procurementDetails: {
      weighbridgeSlipNo: 'WB-9914',
      grossWeightQuintals: 52.0,
      tareWeightQuintals: 7.0,
      netWeightQuintals: 45.0,
      moisturePercent: '15.8% (EXCEEDS LIMIT)',
      foreignMatterPercent: '1.2%',
      verifiedByStaff: 'Inspector M. Kumar',
    },
  },
];

export const MOCK_ACTIVE_BOOKING = MOCK_INITIAL_BOOKINGS[0];

export const MOCK_NOTIFICATIONS = [
  {
    id: 'notif-1',
    type: 'BOOKING_CONFIRMED',
    title: 'Slot Confirmed: Token MY-118',
    message: 'Your slot at Mysore (Bandipalya) APMC Central Yard is confirmed for 50 Qtl Ragi. Monitor live queue remotely.',
    timestamp: '08:32 AM',
    read: false,
    channel: 'SMS & App',
  },
  {
    id: 'notif-2',
    type: 'QUEUE_UPDATE',
    title: 'Live Queue Active at Bandipalya',
    message: 'Procurement active at Gate 2. Currently serving token MY-110. Your position is #8.',
    timestamp: '09:00 AM',
    read: true,
    channel: 'App',
  },
  {
    id: 'notif-3',
    type: 'REMOTE_GUARANTEE',
    title: 'Remote Waiting Advisory',
    message: 'Remote waiting guarantee active. Please do not travel to the yard yet. Next alert at position #5.',
    timestamp: '09:30 AM',
    read: true,
    channel: 'WhatsApp',
  },
];
